:sparkles: Update to GCC 16.1.0, Binutils 2.46, mlibc 6.3.1

diff --git a/GCC/gcc/m2/tools-src/makeSystem b/GCC/gcc/m2/tools-src/makeSystem
--- a/GCC/gcc/m2/tools-src/makeSystem
+++ b/GCC/gcc/m2/tools-src/makeSystem
@@ -2,7 +2,7 @@
 
 # makeSystem creates a target SYSTEM.def using the appropriate dialect template.
 
-# Copyright (C) 2008-2023 Free Software Foundation, Inc.
+# Copyright (C) 2008-2026 Free Software Foundation, Inc.
 # Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.
 #
 # This file is part of GNU Modula-2.
@@ -17,13 +17,13 @@
 # FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# You should have received a copy of the GNU General Public License along
-# with gm2; see the file COPYING.  If not, write to the Free Software
-# Foundation, 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. *)
+# You should have received a copy of the GNU General Public License
+# along with GCC; see the file COPYING3.  If not see
+# <http://www.gnu.org/licenses/>.
 
 
 Usage () {
-   echo "Usage: makesystem dialectflag SYSTEM.def SYSTEM.mod { librarypath } compiler"
+   echo "Usage: makesystem [-gdb] dialectflag SYSTEM.def SYSTEM.mod { librarypath } compiler"
 }
 
 if [ $# -lt 6 ] ; then
@@ -31,6 +31,12 @@ if [ $# -lt 6 ] ; then
    exit 1
 fi
 
+if [ "$1" = "-gdb" ] ; then
+    DEBUG=$1
+    shift
+else
+    DEBUG=""
+fi
 DIALECT=$1
 SYSTEMDEF=$2
 SYSTEMMOD=$3
@@ -101,9 +107,19 @@ displayEnd () {
 MINIMAL="-fno-scaffold-main -fno-scaffold-dynamic -fno-scaffold-static -fno-m2-plugin"
 
 rm -f ${OUTPUTFILE}
-if ${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} \
-	       -c -fdump-system-exports ${SYSTEMMOD} -o /dev/null 2>&1 > /dev/null ; then
-    types=`${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} -fno-m2-plugin -c -fdump-system-exports ${SYSTEMMOD} -o /dev/null | cut -f5 -d' '`
+
+if [ "$DEBUG" != "" ] ; then
+    echo "entering gdb to debug cc1gm2 when using -fdump-system-exports"
+    ${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} \
+		-c -fdump-system-exports ${SYSTEMMOD} -wrapper gdb,--args
+    exit $?
+fi
+
+${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} \
+	    -S -fdump-system-exports ${SYSTEMMOD} -o /dev/null 2>&1 > /dev/null
+res=$?
+if [ ${res} -eq 0 ] ; then
+    types=`${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} -fno-m2-plugin -S -fdump-system-exports ${SYSTEMMOD} -o /dev/null | cut -f5 -d' '`
     touch ${OUTPUTFILE}
     displayStart
     displayExportedTypes
@@ -111,7 +127,9 @@ if ${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} \
     displayBuiltinTypes
     displayEnd
 else
-    ${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} \
-		-c -fdump-system-exports ${SYSTEMMOD} -o /dev/null
-    exit $?
+    echo "the command below failed:"
+    echo "${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} -S -fdump-system-exports ${SYSTEMMOD}"
+    echo "to debug the command use"
+    echo "${COMPILER} ${DIALECT} ${LIBRARY} ${MINIMAL} -S -fdump-system-exports ${SYSTEMMOD} -wrapper gdb,--args"
+    exit $res
 fi
